### ISSUE TITLE
 Error calling API with status code 404 

### ISSUE THREAD

**Issue by changchichung** [zabirauf/AutoGPT.js#16] opened 2023-04-20 01:14 UTC
error log 

```
    Error calling API with status code 404 and message "{

    "error": {

    "message": "The model: `gpt-4` does not exist",

    "type": "invalid_request_error",

    "param": null,

    "code": "model_not_found"

    }

    }

    "
```
what's wrong ? any suggestions ?

**Comment by zabirauf** [comment] 2023-04-20 01:55
@changchichung a fix is in the works.

**Comment by zabirauf** [comment] 2023-04-20 01:59
Closing as duplicate of #13

**Closed by zabirauf** 2023-04-20 01:59 UTC

**Comment by zabirauf** [comment] 2023-04-21 07:15
@changchichung FYI issues should be fixed. I've made the model being used consistent across all plugins based on selection.
